In [29]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [30]:
a = [5]*100                 
b = list(range(1,101))      
data = {"A":a,"B":b}        
df = pd.DataFrame(data)     
df["C"] =df["A"]*df["B"]

In [31]:
df.head()

A  B   C
0  5  1   5
1  5  2  10
2  5  3  15
3  5  4  20
4  5  5  25

In [32]:
X = df[["A", "B"]]     

In [33]:
y= df["C"]

In [34]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [35]:
lm = LinearRegression()

In [36]:
lm.fit(X_train,y_train) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [37]:
prediction = lm.predict(X_test)

In [38]:
prediction

array([110., 375., 160., 420.,  80.,  90., 410., 260., 120., 175.,  25.,
        15., 430., 355., 180., 135., 370.,  65., 305., 310., 495., 205.,
       290., 335., 190., 235., 480.,  45., 185.,  20.])

In [40]:
print(prediction[3])
print(prediction[0])

419.99999999999994
110.00000000000007


In [41]:
print(np.array(y_test))

[110 375 160 420  80  90 410 260 120 175  25  15 430 355 180 135 370  65
 305 310 495 205 290 335 190 235 480  45 185  20]


Линейная регрессия очень хорошо приближает значение произведения, но с небольшой неточностью 

In [42]:
mae = metrics.mean_absolute_error(y_test, prediction)

In [43]:
mae

5.003405097644039e-14

Random forest

In [44]:
forest = RandomForestClassifier(n_jobs=-1, random_state=17)

In [45]:
forest.fit(X_train,y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
                       oob_score=False, random_state=17, verbose=0,
                       warm_start=False)

In [46]:
forest_pred=forest.predict(X_test)

In [47]:
forest_pred

array([105, 380, 155, 415,  75,  95, 405, 255, 115, 170,  35,  10, 425,
       350, 170, 130, 360,  60, 300, 315, 490, 200, 285, 330, 195, 230,
       475,  40, 195,  10])

In [48]:
print(np.array(y_test))

[110 375 160 420  80  90 410 260 120 175  25  15 430 355 180 135 370  65
 305 310 495 205 290 335 190 235 480  45 185  20]


In [49]:
print(metrics.mean_absolute_error(forest_pred, y_test))

5.833333333333333


Дерево решений

In [50]:
clf_tree = DecisionTreeClassifier(criterion='entropy', random_state=17)

In [51]:
clf_tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=17, splitter='best')

In [52]:
tree_pred=clf_tree.predict(X_test)

In [53]:
tree_pred

array([105, 380, 155, 415,  75,  85, 405, 255, 115, 170,  30,  10, 425,
       350, 170, 130, 365,  60, 300, 315, 490, 200, 285, 330, 195, 230,
       475,  40, 195,  10])

In [54]:
print(np.array(y_test))

[110 375 160 420  80  90 410 260 120 175  25  15 430 355 180 135 370  65
 305 310 495 205 290 335 190 235 480  45 185  20]


In [55]:
print(metrics.mean_absolute_error(tree_pred, y_test))

5.5


Как видно, по результатам метрики, лучше всего приближает(но не дает совсем точного значения) линейная регрессия